void* xslAddCall () { return 0; }
void* xslDropCall () { return 0; }
void* xslHandleDebugger () { return 0; }
void* xsltAddKey () { return 0; }
void* xsltAddStackElemList () { return 0; }
void* xsltAddTemplate () { return 0; }
void* xsltAllocateExtra () { return 0; }
void* xsltAllocateExtraCtxt () { return 0; }
void* xsltApplyAttributeSet () { return 0; }
void* xsltApplyImports () { return 0; }
void* xsltApplyOneTemplate () { return 0; }
void* xsltApplyStripSpaces () { return 0; }
void* xsltApplyStylesheet () { return 0; }
void* xsltApplyStylesheetUser () { return 0; }
void* xsltApplyTemplates () { return 0; }
void* xsltAttribute () { return 0; }
void* xsltAttrListTemplateProcess () { return 0; }
void* xsltAttrTemplateProcess () { return 0; }
void* xsltAttrTemplateValueProcess () { return 0; }
void* xsltAttrTemplateValueProcessNode () { return 0; }
void* xsltCalibrateAdjust () { return 0; }
void* xsltCallTemplate () { return 0; }
void* xsltCheckExtPrefix () { return 0; }
void* xsltCheckExtURI () { return 0; }
void* xsltCheckRead () { return 0; }
void* xsltCheckWrite () { return 0; }
void* xsltChoose () { return 0; }
void* xsltCleanupGlobals () { return 0; }
void* xsltCleanupTemplates () { return 0; }
void* xsltComment () { return 0; }
void* xsltCompileAttr () { return 0; }
void* xsltCompilePattern () { return 0; }
void* xsltCompMatchClearCache4 () { return 0; }
void* xsltComputeSortResult () { return 0; }
void* xsltCopy () { return 0; }
void* xsltCopyNamespace () { return 0; }
void* xsltCopyNamespaceList () { return 0; }
void* xsltCopyOf () { return 0; }
void* xsltCopyTextString () { return 0; }
void* xsltCreateRVT () { return 0; }
void* xsltDebug () { return 0; }
void* xsltDebugDumpExtensions () { return 0; }
void* xsltDebugGetDefaultTrace () { return 0; }
void* xsltDebugSetDefaultTrace () { return 0; }
void* xsltDecimalFormatGetByName () { return 0; }
void* xsltDecimalFormatGetByQName0 () { return 0; }
void* xsltDefaultSortFunction () { return 0; }
void* xsltDocumentComp () { return 0; }
void* xsltDocumentElem () { return 0; }
void* xsltDocumentFunction () { return 0; }
void* xsltDocumentSortFunction () { return 0; }
void* xsltDoSortFunction () { return 0; }
void* xsltElement () { return 0; }
void* xsltElementAvailableFunction () { return 0; }
void* xsltEvalAttrValueTemplate () { return 0; }
void* xsltEvalAVT () { return 0; }
void* xsltEvalGlobalVariables () { return 0; }
void* xsltEvalOneUserParam () { return 0; }
void* xsltEvalStaticAttrValueTemplate () { return 0; }
void* xsltEvalTemplateString () { return 0; }
void* xsltEvalUserParams () { return 0; }
void* xsltEvalXPathPredicate () { return 0; }
void* xsltEvalXPathString () { return 0; }
void* xsltEvalXPathStringNs () { return 0; }
void* xsltExtElementLookup () { return 0; }
void* xsltExtensionInstructionResultFinalize8 () { return 0; }
void* xsltExtensionInstructionResultRegister8 () { return 0; }
void* xsltExtModuleElementLookup () { return 0; }
void* xsltExtModuleElementPreComputeLookup () { return 0; }
void* xsltExtModuleFunctionLookup () { return 0; }
void* xsltExtModuleTopLevelLookup () { return 0; }
void* xsltFindDocument () { return 0; }
void* xsltFindElemSpaceHandling () { return 0; }
void* xsltFindTemplate () { return 0; }
void* xsltFlagRVTs0 () { return 0; }
void* xsltForEach () { return 0; }
void* xsltFormatNumberConversion () { return 0; }
void* xsltFormatNumberFunction () { return 0; }
void* xsltFreeAttributeSetsHashes () { return 0; }
void* xsltFreeAVTList () { return 0; }
void* xsltFreeCompMatchList () { return 0; }
void* xsltFreeCtxtExts () { return 0; }
void* xsltFreeDocumentKeys () { return 0; }
void* xsltFreeDocuments () { return 0; }
void* xsltFreeExts () { return 0; }
void* xsltFreeGlobalVariables () { return 0; }
void* xsltFreeKeys () { return 0; }
void* xsltFreeLocale () { return 0; }
void* xsltFreeLocales () { return 0; }
void* xsltFreeNamespaceAliasHashes () { return 0; }
void* xsltFreeRVTs () { return 0; }
void* xsltFreeSecurityPrefs () { return 0; }
void* xsltFreeStackElemList () { return 0; }
void* xsltFreeStyleDocuments () { return 0; }
void* xsltFreeStylePreComps () { return 0; }
void* xsltFreeStylesheet () { return 0; }
void* xsltFreeTemplateHashes () { return 0; }
void* xsltFreeTransformContext () { return 0; }
void* xsltFunctionAvailableFunction () { return 0; }
void* xsltFunctionNodeSet () { return 0; }
void* xsltGenerateIdFunction () { return 0; }
void* xsltGetCNsProp () { return 0; }
void* xsltGetDebuggerStatus () { return 0; }
void* xsltGetDefaultSecurityPrefs () { return 0; }
void* xsltGetExtData () { return 0; }
void* xsltGetExtInfo () { return 0; }
void* xsltGetKey () { return 0; }
void* xsltGetNamespace () { return 0; }
void* xsltGetNsProp () { return 0; }
void* xsltGetPlainNamespace () { return 0; }
void* xsltGetProfileInformation () { return 0; }
void* xsltGetQNameURI () { return 0; }
void* xsltGetQNameURI2 () { return 0; }
void* xsltGetSecurityPrefs () { return 0; }
void* xsltGetSpecialNamespace () { return 0; }
void* xsltGetTemplate () { return 0; }
void* xsltGetUTF8Char () { return 0; }
void* xsltGetXIncludeDefault () { return 0; }
void* xsltIf () { return 0; }
void* xsltInit8 () { return 0; }
void* xsltInitAllDocKeys () { return 0; }
void* xsltInitCtxtExts () { return 0; }
void* xsltInitCtxtKey8 () { return 0; }
void* xsltInitCtxtKeys () { return 0; }
void* xsltInitElemPreComp () { return 0; }
void* xsltInitGlobals () { return 0; }
void* xsltIsBlank () { return 0; }
void* xsltKeyFunction () { return 0; }
void* xsltLoadDocument () { return 0; }
void* xsltLoadStyleDocument () { return 0; }
void* xsltLoadStylesheetPI () { return 0; }
void* xsltLocaleStrcmp () { return 0; }
void* xsltLocalVariablePop () { return 0; }
void* xsltLocalVariablePush () { return 0; }
void* xsltMessage () { return 0; }
void* xsltNamespaceAlias () { return 0; }
void* xsltNeedElemSpaceHandling () { return 0; }
void* xsltNewDocument () { return 0; }
void* xsltNewElemPreComp () { return 0; }
void* xsltNewLocale () { return 0; }
void* xsltNewSecurityPrefs () { return 0; }
void* xsltNewStyleDocument () { return 0; }
void* xsltNewStylesheet () { return 0; }
void* xsltNewTransformContext () { return 0; }
void* xsltNextImport () { return 0; }
void* xsltNormalizeCompSteps () { return 0; }
void* xsltNumber () { return 0; }
void* xsltNumberFormat () { return 0; }
void* xsltParseGlobalParam () { return 0; }
void* xsltParseGlobalVariable () { return 0; }
void* xsltParseStylesheetAttributeSet () { return 0; }
void* xsltParseStylesheetCallerParam () { return 0; }
void* xsltParseStylesheetDoc () { return 0; }
void* xsltParseStylesheetFile () { return 0; }
void* xsltParseStylesheetImport () { return 0; }
void* xsltParseStylesheetImportedDoc () { return 0; }
void* xsltParseStylesheetInclude () { return 0; }
void* xsltParseStylesheetOutput () { return 0; }
void* xsltParseStylesheetParam () { return 0; }
void* xsltParseStylesheetProcess () { return 0; }
void* xsltParseStylesheetUser4 () { return 0; }
void* xsltParseStylesheetVariable () { return 0; }
void* xsltParseTemplateContent () { return 0; }
void* xsltPreComputeExtModuleElement () { return 0; }
void* xsltPrintErrorContext () { return 0; }
void* xsltProcessingInstruction () { return 0; }
void* xsltProcessOneNode () { return 0; }
void* xsltProfileStylesheet () { return 0; }
void* xsltQuoteOneUserParam () { return 0; }
void* xsltQuoteUserParams () { return 0; }
void* xsltRegisterAllElement () { return 0; }
void* xsltRegisterAllExtras () { return 0; }
void* xsltRegisterAllFunctions () { return 0; }
void* xsltRegisterExtElement () { return 0; }
void* xsltRegisterExtFunction () { return 0; }
void* xsltRegisterExtModule () { return 0; }
void* xsltRegisterExtModuleElement () { return 0; }
void* xsltRegisterExtModuleFull () { return 0; }
void* xsltRegisterExtModuleFunction () { return 0; }
void* xsltRegisterExtModuleTopLevel () { return 0; }
void* xsltRegisterExtPrefix () { return 0; }
void* xsltRegisterExtras () { return 0; }
void* xsltRegisterLocalRVT8 () { return 0; }
void* xsltRegisterPersistRVT () { return 0; }
void* xsltRegisterTestModule () { return 0; }
void* xsltRegisterTmpRVT () { return 0; }
void* xsltReleaseRVT8 () { return 0; }
void* xsltResolveStylesheetAttributeSet () { return 0; }
void* xsltRunStylesheet () { return 0; }
void* xsltRunStylesheetUser () { return 0; }
void* xsltSaveProfiling () { return 0; }
void* xsltSaveResultTo () { return 0; }
void* xsltSaveResultToFd () { return 0; }
void* xsltSaveResultToFile () { return 0; }
void* xsltSaveResultToFilename () { return 0; }
void* xsltSaveResultToString () { return 0; }
void* xsltSecurityAllow () { return 0; }
void* xsltSecurityForbid () { return 0; }
void* xsltSetCtxtParseOptions () { return 0; }
void* xsltSetCtxtSecurityPrefs () { return 0; }
void* xsltSetCtxtSortFunc () { return 0; }
void* xsltSetDebuggerCallbacks () { return 0; }
void* xsltSetDebuggerStatus () { return 0; }
void* xsltSetDefaultSecurityPrefs () { return 0; }
void* xsltSetGenericDebugFunc () { return 0; }
void* xsltSetGenericErrorFunc () { return 0; }
void* xsltSetLoaderFunc () { return 0; }
void* xsltSetSecurityPrefs () { return 0; }
void* xsltSetSortFunc () { return 0; }
void* xsltSetTransformErrorFunc () { return 0; }
void* xsltSetXIncludeDefault () { return 0; }
void* xsltShutdownCtxtExts () { return 0; }
void* xsltShutdownExts () { return 0; }
void* xsltSort () { return 0; }
void* xsltSplitQName () { return 0; }
void* xsltStrxfrm () { return 0; }
void* xsltStyleGetExtData () { return 0; }
void* xsltStylePreCompute () { return 0; }
void* xsltSystemPropertyFunction () { return 0; }
void* xsltTemplateProcess () { return 0; }
void* xsltTestCompMatchList () { return 0; }
void* xsltText () { return 0; }
void* xsltTimestamp () { return 0; }
void* xsltTransformError () { return 0; }
void* xsltUninit8 () { return 0; }
void* xsltUnparsedEntityURIFunction () { return 0; }
void* xsltUnregisterExtModule () { return 0; }
void* xsltUnregisterExtModuleElement () { return 0; }
void* xsltUnregisterExtModuleFunction () { return 0; }
void* xsltUnregisterExtModuleTopLevel () { return 0; }
void* xsltValueOf () { return 0; }
void* xsltVariableLookup () { return 0; }
void* xsltXPathCompile () { return 0; }
void* xsltXPathCompileFlags () { return 0; }
void* xsltXPathFunctionLookup () { return 0; }
void* xsltXPathGetTransformContext () { return 0; }
void* xsltXPathVariableLookup () { return 0; }
